name: Sync all branches with main

on:
  push:
    branches:
      - main  # Triggered when a push is made to main

permissions:
  contents: write  # Required to push changes

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set remote URL with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/Paulidex/EAN-Elections.git

      - name: Fetch all branches and tags
        run: git fetch --all --tags

      - name: Sync branches with main
        run: |
          branches=(
            "develop"
            "feature/deployment-and-apk"
            "feature/device-sensors-and-location"
            "feature/firebase-authentication"
            "feature/local-database-sqlite"
            "feature/mvp-data-connection"
            "feature/mvp-ui-navigation"
            "feature/project-setup-and-structure"
            "feature/ui-animations-and-charts"
          )

          for branch in "${branches[@]}"; do
            echo "Processing branch: $branch"

            if git show-ref --verify --quiet refs/heads/$branch; then
              git checkout $branch
            else
              git checkout -b $branch origin/$branch
            fi

            if ! git merge origin/main --no-edit; then
              echo "Conflicts detected on $branch, resolving in favor of main..."
              git checkout --theirs .
              git add .
              git commit -m "Auto-merge main into $branch, conflicts resolved in favor of main"
            fi

            # Forced push with --force-with-lease because branches are not protected
            git push origin $branch --force-with-lease
          done
